export const usuarios = [
  {
    id: 1,
    nombre: "John Doe",
    username: "johndoe",
    correo: "johndoe@example.com",
    telefono: "123-456-7890",
  },
  {
    id: 2,
    nombre: "Jane Smith",
    username: "janesmith",
    correo: "janesmith@example.com",
    telefono: "234-567-8901",
  },
  {
    id: 3,
    nombre: "Michael Johnson",
    username: "michaeljohnson",
    correo: "michaeljohnson@example.com",
    telefono: "345-678-9012",
  },
  {
    id: 4,
    nombre: "Emily Davis",
    username: "emilydavis",
    correo: "emilydavis@example.com",
    telefono: "456-789-0123",
  },
  {
    id: 5,
    nombre: "David Rodriguez",
    username: "davidrodriguez",
    correo: "davidrodriguez@example.com",
    telefono: "567-890-1234",
  },
  {
    id: 6,
    nombre: "Emma Wilson",
    username: "emmawilson",
    correo: "emmawilson@example.com",
    telefono: "678-901-2345",
  },
  {
    id: 7,
    nombre: "Matthew Taylor",
    username: "matthewtaylor",
    correo: "matthewtaylor@example.com",
    telefono: "789-012-3456",
  },
  {
    id: 8,
    nombre: "Olivia Thomas",
    username: "oliviathomas",
    correo: "oliviathomas@example.com",
    telefono: "890-123-4567",
  },
  {
    id: 9,
    nombre: "Daniel Anderson",
    username: "danielanderson",
    correo: "danielanderson@example.com",
    telefono: "901-234-5678",
  },
  {
    id: 10,
    nombre: "Sophia Martinez",
    username: "sophiamartinez",
    correo: "sophiamartinez@example.com",
    telefono: "012-345-6789",
  },
  {
    id: 11,
    nombre: "Jacob Wilson",
    username: "jacobwilson",
    correo: "jacobwilson@example.com",
    telefono: "123-456-7890",
  },
  {
    id: 12,
    nombre: "Isabella Thompson",
    username: "isabellathompson",
    correo: "isabellathompson@example.com",
    telefono: "234-567-8901",
  },
  {
    id: 13,
    nombre: "Ethan Walker",
    username: "ethanwalker",
    correo: "ethanwalker@example.com",
    telefono: "345-678-9012",
  },
  {
    id: 14,
    nombre: "Mia Hernandez",
    username: "miahernandez",
    correo: "miahernandez@example.com",
    telefono: "456-789-0123",
  },
  {
    id: 15,
    nombre: "Alexander Nelson",
    username: "alexandernelson",
    correo: "alexandernelson@example.com",
    telefono: "567-890-1234",
  },
  {
    id: 16,
    nombre: "Ava Martinez",
    username: "avamartinez",
    correo: "avamartinez@example.com",
    telefono: "678-901-2345",
  },
  {
    id: 17,
    nombre: "William Thompson",
    username: "williamthompson",
    correo: "williamthompson@example.com",
    telefono: "789-012-3456",
  },
  {
    id: 18,
    nombre: "Sofia Davis",
    username: "sofiadavis",
    correo: "sofiadavis@example.com",
    telefono: "890-123-4567",
  },
  {
    id: 19,
    nombre: "James Rodriguez",
    username: "jamesrodriguez",
    correo: "jamesrodriguez@example.com",
    telefono: "901-234-5678",
  },
  {
    id: 20,
    nombre: "Abigail Wilson",
    username: "abigailwilson",
    correo: "abigailwilson@example.com",
    telefono: "012-345-6789",
  },
  {
    id: 21,
    nombre: "Benjamin Smith",
    username: "benjaminsmith",
    correo: "benjaminsmith@example.com",
    telefono: "123-456-7890",
  },
  {
    id: 22,
    nombre: "Charlotte Davis",
    username: "charlottedavis",
    correo: "charlottedavis@example.com",
    telefono: "234-567-8901",
  },
  {
    id: 23,
    nombre: "Joseph Johnson",
    username: "josephjohnson",
    correo: "josephjohnson@example.com",
    telefono: "345-678-9012",
  },
  {
    id: 24,
    nombre: "Harper Wilson",
    username: "harperwilson",
    correo: "harperwilson@example.com",
    telefono: "456-789-0123",
  },
  {
    id: 25,
    nombre: "Henry Martinez",
    username: "henrymartinez",
    correo: "henrymartinez@example.com",
    telefono: "567-890-1234",
  },
  {
    id: 26,
    nombre: "Amelia Davis",
    username: "ameliadavis",
    correo: "ameliadavis@example.com",
    telefono: "678-901-2345",
  },
  {
    id: 27,
    nombre: "Liam Taylor",
    username: "liamtaylor",
    correo: "liamtaylor@example.com",
    telefono: "789-012-3456",
  },
  {
    id: 28,
    nombre: "Elizabeth Anderson",
    username: "elizabethanderson",
    correo: "elizabethanderson@example.com",
    telefono: "890-123-4567",
  },
  {
    id: 29,
    nombre: "Sebastian Walker",
    username: "sebastianwalker",
    correo: "sebastianwalker@example.com",
    telefono: "901-234-5678",
  },
  {
    id: 30,
    nombre: "Evelyn Thompson",
    username: "evelynthompson",
    correo: "evelynthompson@example.com",
    telefono: "012-345-6789",
  },
];
