const ventas = [
  {
    id: 1,
    producto: 'Camisa',
    precio: 29.99,
    cantidadVendida: 3,
    metodoPago: 'Tarjeta de crédito',
  },
  {
    id: 2,
    producto: 'Pantalón',
    precio: 49.99,
    cantidadVendida: 2,
    metodoPago: 'Efectivo',
  },
  {
    id: 3,
    producto: 'Zapatos',
    precio: 89.99,
    cantidadVendida: 1,
    metodoPago: 'PayPal',
  },
  {
    id: 4,
    producto: 'Blusa',
    precio: 39.99,
    cantidadVendida: 4,
    metodoPago: 'Transferencia bancaria',
  },
  {
    id: 5,
    producto: 'Shorts',
    precio: 19.99,
    cantidadVendida: 2,
    metodoPago: 'Tarjeta de crédito',
  },
  {
    id: 6,
    producto: 'Vestido',
    precio: 69.99,
    cantidadVendida: 1,
    metodoPago: 'Efectivo',
  },
  {
    id: 7,
    producto: 'Zapatos deportivos',
    precio: 79.99,
    cantidadVendida: 2,
    metodoPago: 'PayPal',
  },
  {
    id: 8,
    producto: 'Chaqueta',
    precio: 99.99,
    cantidadVendida: 1,
    metodoPago: 'Transferencia bancaria',
  },
  {
    id: 9,
    producto: 'Jeans',
    precio: 59.99,
    cantidadVendida: 3,
    metodoPago: 'Tarjeta de crédito',
  },
  {
    id: 10,
    producto: 'Blusa estampada',
    precio: 34.99,
    cantidadVendida: 2,
    metodoPago: 'Efectivo',
  },
  {
    id: 11,
    producto: 'Bolso',
    precio: 49.99,
    cantidadVendida: 1,
    metodoPago: 'PayPal',
  },
  {
    id: 12,
    producto: 'Zapatos de tacón',
    precio: 89.99,
    cantidadVendida: 1,
    metodoPago: 'Transferencia bancaria',
  },
  {
    id: 13,
    producto: 'Gorra',
    precio: 14.99,
    cantidadVendida: 4,
    metodoPago: 'Tarjeta de crédito',
  },
  {
    id: 14,
    producto: 'Sudadera',
    precio: 44.99,
    cantidadVendida: 2,
    metodoPago: 'Efectivo',
  },
  {
    id: 15,
    producto: 'Calcetines',
    precio: 9.99,
    cantidadVendida: 5,
    metodoPago: 'PayPal',
  },
  {
    id: 16,
    producto: 'Cinturón',
    precio: 19.99,
    cantidadVendida: 3,
    metodoPago: 'Transferencia bancaria',
  },
  {
    id: 17,
    producto: 'Blazer',
    precio: 79.99,
    cantidadVendida: 1,
    metodoPago: 'Tarjeta de crédito',
  },
  {
    id: 18,
    producto: 'Polo',
    precio: 24.99,
    cantidadVendida: 2,
    metodoPago: 'Efectivo',
  },
  {
    id: 19,
    producto: 'Falda',
    precio: 39.99,
    cantidadVendida: 1,
    metodoPago: 'PayPal',
  },
  {
    id: 20,
    producto: 'Botas',
    precio: 79.99,
    cantidadVendida: 1,
    metodoPago: 'Transferencia bancaria',
  },
];

export default ventas;

  