const PUT_PASSWORD = "PUT_PASSWORD";
const CREATE_USER = "CREATE_USER";
const GET_PRODUCT = "GET_PRODUCT";
const GET_PRODUCTS = "GET_PRODUCTS";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const EDIT_PRODUCT = "EDIT_PRODUCT";
const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY";
const USER_LOGIN = "USER_LOGIN";
const GET_USERS = "GET_USERS";
const DELETE_USER = "DELETE_USER";
const PROMOTE_USER = "PROMOTE_USER";
const LOGIN_USER = "LOGIN_USER";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const GET_CARTG = "GET_CARTG";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const UPDATE_PRODUCT_LIST = "UPDATE_PRODUCT_LIST";
const RESET_FILTER = "RESET_FILTER";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
const SET_CART = "SET_CART";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_PRODUCTS_PER_PAGE = "SET_PRODUCTS_PER_PAGE";

export {
  PUT_PASSWORD,
  CREATE_USER,
  GET_PRODUCT,
  GET_PRODUCTS,
  DELETE_PRODUCT,
  EDIT_PRODUCT,
  GET_PRODUCT_CATEGORY,
  USER_LOGIN,
  GET_USERS,
  DELETE_USER,
  PROMOTE_USER,
  LOGIN_USER,
  GET_ALL_PRODUCTS,
  GET_CARTG,
  FILTER_PRODUCTS,
  UPDATE_PRODUCT_LIST,
  RESET_FILTER,
  ADD_TO_CART,
  REMOVE_ONE_FROM_CART,
  REMOVE_ALL_FROM_CART,
  SET_CART,
  SET_CURRENT_PAGE,
	SET_PRODUCTS_PER_PAGE
};
